In [64]:
import pandas as pd

In [65]:
dataset=pd.read_csv("insurance_pre.csv")

In [66]:
dataset=pd.get_dummies(dataset, drop_first=True)

In [67]:
dataset=dataset.astype(int)

In [68]:
dataset

,age,bmi,children,charges,sex_male,smoker_yes
0,19,27,0,16884,0,1
1,18,33,1,1725,1,0
2,28,33,3,4449,1,0
3,33,22,0,21984,1,0
4,32,28,0,3866,1,0
...,...,...,...,...,...,...
1333,50,30,3,10600,1,0
1334,18,31,0,2205,0,0
1335,18,36,0,1629,0,0
1336,21,25,0,2007,0,0


In [69]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [70]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dependent=dataset[[ 'charges']]

In [71]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(independent, dependent, test_size=0.20, random_state=0)

In [72]:
# CASE 1: Preprocess input from training/test data set and the user input (preinput variable)

In [73]:
# Preprocess only input training and test data
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [74]:
from sklearn.svm import SVR
regressor=SVR(kernel="rbf",C=1000)
regressor.fit(X_train, Y_train)

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


,kernel,'rbf'
,degree,3
,gamma,'scale'
,coef0,0.0
,tol,0.001
,C,1000
,epsilon,0.1
,shrinking,True
,cache_size,200
,verbose,False
,max_iter,-1


In [75]:
Y_Pred=regressor.predict(X_test)
Y_Pred

array([10189.50183286,  8848.49384476, 40895.5064764 , 12668.48547368,
       10405.71129613,  4093.03087946,  2275.76154843, 11429.39263349,
        7186.46305574,  5069.87948751,  7386.71577115, 10531.74487347,
        7550.08740833,  4366.99586107, 23420.35134702, 11190.70474912,
       12450.45097817,  2923.69165401,  6444.8670852 , 24116.46735057,
       24271.02382659, 12879.69749279, 10088.65582567, 28037.32728648,
        1830.46950591,  3797.18987254,  4422.83001808,  7716.21585582,
        3898.77600295,  8524.15326141,  7832.61296669, 36969.82653281,
       13049.50744754, 10522.80148605, 14413.66484153,  3685.69973653,
        8463.8627991 , 37733.74187667, 35578.43870485,  2190.70045844,
        5633.21256425,  2979.58959225, 23729.1308547 , 38763.79412848,
       29440.01517482,  3821.49426123, 11183.77072329,  6857.98442668,
        4038.25933635, 12181.9943767 ,  2406.46396331,  4646.68274393,
       30795.45325789, 34253.25737736, 12089.92451002,  2601.74903582,
      

In [76]:
from sklearn.metrics import r2_score
r_score=r2_score(Y_test, Y_Pred)
r_score

0.8252164693926967

In [77]:
# Preprocessing the user input before predicting the output of the user input
# Note, we have not preprocess the output for user input
preinput=sc.transform([[52,30.2,1,1,0]])
preinput

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[ 0.91668389, -0.00602245, -0.06565939,  1.01506676, -0.50729114]])

In [78]:
Predict_UserInput=regressor.predict(preinput)
Predict_UserInput

array([10185.15295002])

In [79]:
# CASE 2: 
#- Preprocess input and output from training/test data set 
#- Preprocess user input
#- Inverse preprocessed output

In [80]:
from sklearn.preprocessing import StandardScaler
scx=StandardScaler()
X_train=scx.fit_transform(X_train)
X_test=scx.transform(X_test)

scy=StandardScaler()
Y_train=scy.fit_transform(Y_train)
Y_test=scy.transform(Y_test)

In [81]:
X_train

array([[-0.14853305,  0.60616004,  2.41394802,  1.01506676,  1.97125461],
       [-1.49780784,  0.60616004, -0.89219519,  1.01506676, -0.50729114],
       [-1.14273553,  0.92836135,  0.76087642, -0.98515688,  1.97125461],
       ...,
       [ 0.06451033, -0.84374587, -0.89219519,  1.01506676, -0.50729114],
       [-1.42679338,  0.7672607 , -0.89219519,  1.01506676, -0.50729114],
       [-0.4325909 , -1.97145047, -0.06565939, -0.98515688, -0.50729114]],
      shape=(1070, 5))

In [82]:
from sklearn.svm import SVR
regressor=SVR(kernel="rbf", C=1000)
regressor=regressor.fit(X_train, Y_train)

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [83]:
Y_Pred_1=regressor.predict(X_test)

In [84]:
from sklearn.metrics import r2_score 
r_score=r2_score(Y_test, Y_Pred_1) 
r_score

0.8242906357882999

In [85]:
# Preprocessing the user input before predicting the output of the user input
# Note, we are going to preprocess the output for user input and then reverse it to show it to user
preinput_1=scx.transform([[52,30.2,1,1,0]])
preinput_1

array([[ 5.20000000e+01,  3.02000000e+01,  1.00000000e+00,
         1.00000000e+00, -2.98826384e-17]])

In [86]:
Predict_UserInputOutput=regressor.predict(preinput_1)
Predict_UserInputOutput

array([0.00531478])

In [87]:
#Preoutput=scy.inverse_transform(Predict_UserInputOutput.reshape(-1,1))
Preoutput=scy.inverse_transform([Predict_UserInputOutput])
Preoutput

array([[13264.32840008]])